### PR TITLE
Added sensitivity flag to rundeck-config.properites template

### PR DESCRIPTION
**Pull request by isuftin**
May contain sensitive information if using plaintext password for providers for Jasypt encryption plugin

### CODE REVIEW

**Comment by kamaradclimber** [comment]
thanks @isuftin for your contribution. I think there is a typo in your patch: s/sansitive/sensitive.

Tests are failing because travis does not want to decrypt the keys for ec2, @dlukman could you have a look to deactivate key decryption on external merge requests?

**Comment by isuftin** [comment]
@kamaradclimber Fixed ;)

**Comment by isuftin** [comment]
I suck at git, apparently (not too easy to fix typos in commits that are not the last commit). Will reopen.

**Comment by kamaradclimber** [comment]
Thanks!

**Pull request closed without merging**
