### PR TITLE
Update default recipe to intelligently figure out what the Rundeck endpoint is for testing

### PR DESCRIPTION
**Pull request by isuftin**

### CODE REVIEW

**Comment by isuftin** [comment]
@kamaradclimber I'm not sure that my change is what's causing failing tests in Travis. How are you running these tests locally?

**Comment by kamaradclimber** [comment]
I'll have a quick look

**Comment by kamaradclimber** [comment]
it seems that rebasing on https://github.com/criteo-cookbooks/rundeck-server/commit/bc3f50ba91d51d8b9faa9c737468f2ffa63b01b4 helps

**Comment by kamaradclimber** [comment]
merging your patch

**Comment by kamaradclimber** [comment]
thanks for the contribution!

**Comment by kamaradclimber** [comment]
hum something is not working completely right, I should have a look

**Pull request merged**
