### PR TITLE
Allow some sensitive configuration elements to come from an encrypted data bag

### PR DESCRIPTION
**Pull request by isuftin**

### CODE REVIEW

**Comment by isuftin** [comment]
Not sure why the previous commits I made here are still part of this PR even though I merged with your master branch?

**Comment by kamaradclimber** [comment]
I've rebased your change when I accepted your last PR. Could you rebase this one on master ?
It should make disappear the duplicte commit.

**Comment by kamaradclimber** [comment]
thanks for this new contribution by the way.

I've mixed feeling about this feature though. This is the kind of refinement that seems to belong to a wrapper cookbook.
Some people use encrypted databags, some use chef-vault (that's what we do), so I'm quite relunctant to make this cookbook a bit more complex than necessary.

@rveznaver any opinion?

**Comment by rveznaver** [comment]
Hi @isuftin, thank you for your PR, but I share @kamaradclimber's opinion. As the secrets distribution landscape is quite diverse (ranging from HashiCorp's Vault to homegrown services like CERN's Teigi) I would prefer to keep it out of this cookbook unless something absolutely cannot be done in a wrapper cookbook.

**Comment by isuftin** [comment]
The thing to note about this PR is that this feature for using an encrypted databag is completely optional. Not using it does not break the current functionality of the cookbook.

I do have a wrapper cookbook for this but the issue is that ultimately, it's a bit tricky to inject sensitive values into node attributes to make its way into templates and then to remove those values from attributes at the end of the run so those values don't stick around in plain-text available to knife commands, chef console, etc.

Here's the pertinent section in my wrapper cookbook we use in our organization: https://github.com/isuftin/chef-cookbook-caws-rundeck/blob/master/recipes/default.rb

As you can see, it's a bit of work to achieve security here.

Do you guys have a different way that you achieve this functionality?

Also, can we at least make some of the templating sensitive? The secrets show up in Chef client-run logs at least the first time the templates write out.

**Comment by rveznaver** [comment]
Yup, we inject and then hide them with [chef-secrets](https://github.com/criteo-cookbooks/chef-secrets).

As far as I am concerned we can make all templates sensitive (I think some already are). A separate PR would be easier to read (wink, wink) :)

**Pull request closed without merging**
